vim.opt.rtp:prepend(assert(vim.env.NVIM_CONFIG_ROOT))
local c = require("config")
local base = c.resolve({}, {}, {})
assert(#c.plan(base).tools == 0)
assert(not base.languages.go and not base.features.ai)
local dev = c.resolve({ profile = "developer" }, {}, {})
assert(dev.languages.go and dev.languages.rust and not dev.languages.tex)
local preset = c.resolve({ languages = { lua = true } }, {}, {}, "developer")
assert(preset.languages.go and preset.languages.lua)
local off = c.resolve({ features = { ai = true, copilot = true } }, {}, { NVIM_OFFLINE = "1", NVIM_FEATURES = "ai,copilot" })
assert(not off.features.ai and not off.features.copilot)
assert(off.sources["features.ai"] == "offline")
assert(not pcall(c.resolve, { features = { typo = true } }, {}, {}))
assert(not pcall(c.resolve, {}, {}, { NVIM_FEATURES = "dap=typo" }))
local precedence = c.resolve({ languages = { go = true } }, { languages = { go = false } }, { NVIM_LANGUAGES = "go" })
assert(precedence.languages.go and precedence.sources["languages.go"] == "env")
assert(not vim.tbl_contains(c.plan(dev).tools, "debugpy"))
dev.features.dap = true
assert(vim.tbl_contains(c.plan(dev).tools, "debugpy"))
print("配置优先级、校验、按需工具和离线约束通过")
vim.cmd.qa()
