local M = {
    -- Dirs
    dap = require("modules.dap"),
    lsp = require("modules.lsp"),

    -- Plugins
    accelerated_jk = require("modules.accelerated-jk"),
    alpha = require("modules.alpha"),
    autolist = require("modules.autolist"),
    autopairs = require("modules.autopairs"),
    bigfile = require("modules.bigfile"),
    bufferline = require("modules.bufferline"),
    catppuccin = require("modules.catppuccin"),
    cmp = require("modules.cmp"),
    colorizer = require("modules.colorizer"),
    comment = require("modules.comment"),
    copilot = require("modules.copilot"),
    crates = require("modules.crates"),
    diffview = require("modules.diffview"),
    dressing = require("modules.dressing"),
    esqueleto = require("modules.esqueleto"),
    gitsigns = require("modules.gitsigns"),
    hex = require("modules.hex"),
    hop = require("modules.hop"),
    hydra = require("modules.hydra"),
    indentline = require("modules.indentline"),
    lualine = require("modules.lualine"),
    navic = require("modules.navic"),
    neoclip = require("modules.neoclip"),
    neoconf = require("modules.neoconf"),
    neogit = require("modules.neogit"),
    neorg = require("modules.neorg"),
    neoscroll = require("modules.neoscroll"),
    noice = require("modules.noice"),
    notify = require("modules.notify"),
    nvim_surround = require("modules.nvim-surround"),
    nvim_tree = require("modules.nvim-tree"),
    nvim_gdb = require("modules.nvim_gdb"),
    nvim_lastplace = require("modules.nvim_lastplace"),
    portal = require("modules.portal"),
    pretty_fold = require("modules.pretty_fold"),
    session_manager = require("modules.session_manager"),
    smartyank = require("modules.smartyank"),
    sniprun = require("modules.sniprun"),
    spectre = require("modules.spectre"),
    spellsitter = require("modules.spellsitter"),
    symbols_outline = require("modules.symbols_outline"),
    telescope = require("modules.telescope"),
    tmux = require("modules.tmux"),
    toggleterm = require("modules.toggleterm"),
    treesitter_context = require("modules.treesitter-context"),
    treesitter = require("modules.treesitter"),
    trouble = require("modules.trouble"),
    undotree = require("modules.undotree"),
    venv_selector = require("modules.venv-selector"),
    whichkey = require("modules.whichkey"),
    zfvimim = require("modules.zfvimim"),
}

return M
