require("modules.alpha")
require("modules.aerial")
-- require("modules.autosave")
require("modules.autopairs")
require("modules.bufferline")
require("modules.catppuccin")
require("modules.cmp")
require("modules.colorizer")
require("modules.comment")
require("modules.filetype")
require("modules.gitsigns")
require("modules.gps")
require("modules.hop")
require("modules.impatient")
require("modules.indentline")
require("modules.lualine")
require("modules.lsp")
require("modules.nvim-tree")
require("modules.project")
require("modules.session_manager")
require("modules.sniprun")
require("modules.telescope")
require("modules.vim-templates")
require("modules.trouble")
require("modules.toggleterm")
require("modules.treesitter")
require("modules.treesitter-context")
require("modules.undotree")
require("modules.whichkey")

-- FUTURE: add tmux integrity
-- FUTURE: Remote development
