vim.opt.rtp:prepend(assert(vim.env.NVIM_CONFIG_ROOT))
local c = require("config").get()
local text = "-- Machine-specific selections saved by the installer.\nreturn " .. vim.inspect({ profile = c.profile, languages = c.languages, features = c.features })
vim.fn.writefile(vim.split(text, "\n", { plain = true }), vim.env.NVIM_CONFIG_ROOT .. "/lua/config/local.lua")
vim.cmd.qa()
