local function map(lhs, rhs, desc)
    vim.keymap.set("n", lhs, rhs, { silent = true, desc = desc })
end
local function save()
    if pcall(vim.cmd, "write") then return end
    local ok, err = pcall(vim.cmd, "SudaWrite")
    if not ok then vim.notify("Save failed: " .. tostring(err), vim.log.levels.ERROR) end
end
map("<leader>w", save, "Save")
map("<leader>e", "<cmd>edit<cr>", "Reload")
map("H", "<cmd>bprevious<cr>", "Previous Buffer")
map("L", "<cmd>bnext<cr>", "Next Buffer")
vim.keymap.set("n", "<CR>", function()
    return vim.fn.foldclosed(".") >= 0 and "zo" or "<CR>"
end, { expr = true, silent = true, desc = "Expand Fold" })
map("[b", "<cmd>bprevious<cr>", "Previous Buffer")
map("]b", "<cmd>bnext<cr>", "Next Buffer")
map("<C-h>", "<C-w>h", "Focus Left Window")
map("<C-j>", "<C-w>j", "Focus Lower Window")
map("<C-k>", "<C-w>k", "Focus Upper Window")
map("<C-l>", "<C-w>l", "Focus Right Window")
map("<M-Up>", "<cmd>resize -2<cr>", "Decrease Window Height")
map("<M-Down>", "<cmd>resize +2<cr>", "Increase Window Height")
map("<M-Left>", "<cmd>vertical resize -2<cr>", "Decrease Window Width")
map("<M-Right>", "<cmd>vertical resize +2<cr>", "Increase Window Width")
map("<leader>c", function()
    if package.loaded.snacks then Snacks.bufdelete() else vim.cmd.bdelete() end
end, "Close Buffer")
map("<leader>xi", "<cmd>ConfigInfo<cr>", "Configuration Info")
map("<leader>xh", "<cmd>checkhealth config<cr>", "Configuration Health")
map("<leader>h", "<cmd>nohlsearch<cr>", "Clear Search Highlight")
map("<leader>q", "<cmd>x<cr>", "Close Window")
map("<leader>Q", "<cmd>xa<cr>", "Quit Neovim")
vim.keymap.set("i", "jk", "<esc>", { silent = true, desc = "Escape" })
vim.keymap.set("v", "J", ":m .+1<cr>==", { silent = true, desc = "Move Selection Down" })
vim.keymap.set("v", "K", ":m .-2<cr>==", { silent = true, desc = "Move Selection Up" })
vim.keymap.set("v", "p", '"_dP', { silent = true, desc = "Paste Without Replacing Register" })
vim.keymap.set("x", "J", ":move '>+1<cr>gv-gv", { silent = true, desc = "Move Selection Down" })
vim.keymap.set("x", "K", ":move '<-2<cr>gv-gv", { silent = true, desc = "Move Selection Up" })
