local function map(lhs, rhs, desc)
    vim.keymap.set("n", lhs, rhs, { silent = true, desc = desc })
end
map("<leader>w", "<cmd>write<cr>", "Save")
map("<leader>r", "<cmd>edit<cr>", "Reload")
map("<leader>bn", "<cmd>bnext<cr>", "Next Buffer")
map("<leader>bp", "<cmd>bprevious<cr>", "Previous Buffer")
map("<leader>bd", "<cmd>bdelete<cr>", "Delete Buffer")
map("<leader>xv", "<cmd>vsplit<cr>", "Vertical Split")
map("<leader>xs", "<cmd>split<cr>", "Horizontal Split")
map("<leader>xq", "<cmd>close<cr>", "Close Window")
map("<leader>xe", "<C-w>=", "Equalize Windows")
map("<leader>ui", "<cmd>ConfigInfo<cr>", "Configuration Info")
map("<leader>uh", "<cmd>checkhealth config<cr>", "Configuration Health")
map("<leader>un", "<cmd>nohlsearch<cr>", "Clear Search Highlight")
